name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit
  workflow_dispatch:  # Permet l'exécution manuelle

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Add original repo as remote
      run: |
        git remote add upstream https://github.com/open-webui/open-webui.git

    - name: Fetch upstream changes
      run: |
        git fetch upstream

    - name: Check for changes
      id: check_changes
      run: |
        git fetch upstream
        if git diff --quiet upstream/main origin/main; then
          echo "No changes detected"
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected"
          echo "changes=true" >> $GITHUB_OUTPUT
          git merge upstream/main
        fi

    - name: Debug output
      run: |
        echo "Changes detected: ${{ steps.check_changes.outputs.changes }}"

    - name: Push changes if any
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git push origin main

    - name: Create Pull Request
      if: steps.check_changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        branch: sync-fork
        title: 'Sync fork with upstream repository'
        body: 'This PR syncs changes from the upstream repository. Please review and merge.'
        commit-message: 'Sync fork with upstream repository'
        delete-branch: true